# Generated by Django 3.0.2 on 2020-01-14 12:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20200114_0920'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ArticleImage',
        ),
    ]
